name: build

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=src" >> $GITHUB_ENV
      - name: Test with pytest
        env: 
          NYCKEL_PYTHON_SDK_CLIENT_SECRET: ${{ secrets.NYCKEL_PYTHON_SDK_CLIENT_SECRET }}
        run: |
          pytest -s
      - name: Install build dependencies
        run: |
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}