name: docs 
on: 
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MKDOCSTRINGS_SSH_KEY }}
      - run: git clone git@github.com:NyckelAI/mkdocstrings-python.git
      - run: pip install -e mkdocstrings-python
      - run: pip install mkdocs-material==9.4.5
      - run: mkdocs gh-deploy --force